export const GET_CANDIDATE_INTERVIEWS = "GET_CANDIDATE_INTERVIEWS";
export const SET_CANDIDATE_INTERVIEWS = "GET_CANDIDATE_INTERVIEWS";
export const SET_CANDIDATE_ARCHIVED_STATUS_ACTIVE =
  "SET_CANDIDATE_ARCHIVED_STATUS_ACTIVE";
export const SET_CANDIDATE_ARCHIVED_STATUS_INACTIVE =
  "SET_CANDIDATE_ARCHIVED_STATUS_INACTIVE";
export const SET_CANDIDATE_INTERVIEWS_LOADING =
  "SET_CANDISATE_INTERVIEW_LOADING";
export const SET_CANDIDATE_ARCHIVED_STATUS_ERROR =
  "SET_CANDIDATE_ARCHIVED_STATUS_ERROR";
